"""Create initial models

Revision ID: 1880a8982b2f
Revises: 
Create Date: 2023-09-13 09:40:06.635938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1880a8982b2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sjcattendance_resolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('complementary', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sjcattendance_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('course_uuid', sa.Uuid(), nullable=False),
    sa.Column('student_uuid', sa.Uuid(), nullable=False),
    sa.Column('resolution', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolution'], ['sjcattendance_resolution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sjcattendance_attendance')
    op.drop_table('sjcattendance_resolution')
    # ### end Alembic commands ###
