test-frontend:
  stage: test
  image: node:20-alpine
  script:
    - cd frontend
    - npm ci
    - npm run test

deploy-frontend:
  stage: deploy
  image: node:20-alpine
  before_script:
    - apk update && apk add aws-cli
  script:
    - cd frontend
    - npm ci --production
    - npm run build
    - aws s3 sync --delete dist s3://sjcadmin-frontend
  only:
    refs:
      - main
    changes:
      - frontend/**/*
  variables:
    AWS_ACCESS_KEY_ID: $DEPLOY_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $DEPLOY_AWS_SECRET_ACCESS_KEY
