deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - cd workers/attendance
    - apk add --update npm #python3 curl
    - npm ci
    - npm install -g serverless
    # - curl -sSL https://install.python-poetry.org | python3 -
  script:
    - sls deploy --stage prod
  only:
    - main
    - feature/attendance-app  # Remove
  variables:
    AWS_ACCESS_KEY_ID: $TERRAFORM_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $TERRAFORM_AWS_SECRET_ACCESS_KEY
