FROM python:3.10-bullseye

ENV PATH="/root/.local/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | python3 -

# COPY poetry.* pyproject.toml /app/
# WORKDIR /app
# ENV POETRY_VIRTUALENVS_IN_PROJECT="true"
# RUN poetry install --without dev --sync
