service: sjcadmin-attendance-worker
frameworkVersion: "3"

provider:
  name: aws
  deploymentBucket:
    name: serverless-eu-west-2-082624796438
  ecr:
    images:
      attendance-consumer:
        path: ./
  region: eu-west-2

  # runtime: python3.10

constructs:
  jobs:
    type: queue
    worker:
      image: attendance-consumer

# functions:
#   producer:
#     handler: handler.producer
#     events:
#       - httpApi:
#           method: post
#           path: /produce
#     environment:
#       QUEUE_URL: ${construct:jobs.queueUrl}

plugins:
  - serverless-lift
  # - serverless-python-requirements

package:
  patterns:
    - "!node_modules/**"
