service: sjcadmin-attendance-worker
frameworkVersion: "3"

provider:
  name: aws
  deploymentBucket:
    name: serverless-eu-west-2-082624796438
  ecr:
    images:
      attendance-consumer:
        path: ./
  region: eu-west-2
  iam:
    role:
      statements:
        - Effect: Allow
          Principal:
            Service:
             - sns.amazonaws.com
          Action:
            - sqs:SendMessage
          Resource: ${construct:jobs.queueUrl}
          Condition:
            ArnEquals: !ImportValue sns-event-${sls:stage}

custom:
  arnAttendanceTopic:
    Fn::ImportValue: AttendanceTopicArn

constructs:
  jobs:
    type: queue
    worker:
      image: attendance-consumer

resources:
  Resources:
    Subscription:
      Type: "AWS::SNS::Subscription"
      Properties:
        Endpoint: ${construct:jobs.queueArn}
        Protocol: sqs
        TopicArn: ${self:custom.arnAttendanceTopic}

plugins:
  - serverless-lift

package:
  patterns:
    - "!node_modules/**"
