# Generated by Django 4.1.2 on 2022-10-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='licence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sjcadmin.licence'),
        ),
    ]
