# Generated by Django 4.1.3 on 2022-11-19 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sjcadmin', '0004_student_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_text', models.TextField(blank=True, db_column='text')),
                ('_datetime', models.DateTimeField(db_column='datetime')),
                ('_author', models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('_student', models.ForeignKey(db_column='student_uuid', on_delete=django.db.models.deletion.CASCADE, to='sjcadmin.student')),
            ],
        ),
    ]
