# Generated by Django 4.1.3 on 2022-12-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0005_alter_student_join_date_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_datetime', models.DateTimeField(db_column='datetime')),
                ('_used', models.BooleanField(default=False)),
                ('_student', models.ForeignKey(db_column='student_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sjcadmin.student')),
            ],
        ),
    ]
