# Generated by Django 4.1.3 on 2022-12-26 21:58

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('_uuid', models.UUIDField(db_column='uuid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_label', models.CharField(db_column='label', max_length=30, null=True)),
                ('_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='days', size=7)),
            ],
        ),
    ]
