include:
  - services/docker-compose.yml
  - workers/docker-compose.yml

services:
  frontend:
    image: node:20-alpine
    command: ["npm", "run", "dev"]
    depends_on:
      - gateway
    working_dir: /app
    volumes:
      - ./frontend:/app

  app:
    build:
      context: .
      target: prod-runtime
    image: 082624796438.dkr.ecr.eu-west-2.amazonaws.com/sjcadmin/app
    depends_on:
      - database
    environment:
      - API_ROOT=http://api.southamptonjiujitsu.local:9000
      - API_KEY=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZiB5b3UgYXJlIHJlYWRpbmcgdGhpcyI6InlvdSBoYXZlIHRvbyBtdWNoIHRpbWUgb24geW91ciBoYW5kcyJ9.a2Vm6eY2cbWIhwteh1lK3zn8sb6gH7rk38SNtnm_6XKvz2vnNqajXx2uxYtF7Cwl9n-f1Vn7FVg8y2OwWknkqDg3OY2leNN6GbDvdZpDiafYipVssOqo3Lq361vQCzSHtHnBlMu_Gf_EIwSqT1gsAtRwJlZ2oOD_otIVlpap7bU
      - DJANGO_SETTINGS_MODULE=sjcadmin.settings
      - DJANGO_SECRET_KEY="*(%z)+p^f+*&!zdv$j_ipce+)ru+f+g91udo2i&=1l1r6deyet"
      - ENVIRONMENT_NAME=local
      - PGHOST=database
      - PGPASS=Rand0m!
      - SJJ_S3_ACCESS_KEY=AKIARGPGSK4LMB2A3YFS
      - SJJ_S3_SECRET_KEY=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
      - EMAIL_HOST=mail
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=false
      - EMAIL_HOST_USER='username'
      - EMAIL_HOST_PASSWORD='password'
      - PRIV_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNkUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQWw4d2dnSmJBZ0VBQW9HQkFPUU9oeEhFaU1wdjBEdnYKZVZlcUxRTjROR3RxOHRKZU0wZ3BRVkgzekUyNGx2a2dwOG80V3JEU3hnb3FJRmdDUjJPZzl1eXhqNmt2alhleAorS3QzeFN1Z1RFaXoreGt2WUFKWHNkc3BMS1ZTTVFYT0NGODErUTFRVFZxV1ZUeWQ1YzloWHNtblYzQ1ZSRTJlCit4WlFoVDhZMkZqdm5DVmhXQml3WUNpQXBPd2xBZ01CQUFFQ2dZQURKeGhDN0o2ZmZkQTVJK1JmaStDM2JZLzcKOUN5TEwvWXhoekI1KzV6OWJoSFlPOVZWL0ZWMG9GVlFpcWlMenV4QnVsWHZpN3phcitlYXdnRVlEYjNTQitUcwo4V1QvQXUzYmVyY2lzRXB4cGNrYmJNWC85blkrN21ISS96SmNMUFVEOUFOSFVYbUVHY1BrZDF4Ym5NRTNURGlvCmtIc1dsR09nZFdpSk1Sd1NPUUpCQVBRNVQ2Q2NyOVZCZ3JkeVp6Z2Z5bTBBZkZ5cmxyZ0FBMzZUTWxsWWtYN3AKTUF5dm9Kc3JjaXM2c3ppdGpESzBhRUV0RmNmYmRTblpXRytaZ3hTR0l2Y0NRUUR2RGFaNlBQUmtuR2U2b29SKwpBck5GbkxLNi9hSi9tL2IrSzF0akNDWHlBWE9Hb2NsVVJZdFZJVVhYcU5CeE9EM2FnY2xWRDRGMW1hTWpySHNqCmJZYkRBa0EzcUxnVkNxQ29JWDRCQVBtMU9NbVJmZ0xadStGbG5kc3VCYTM3M3N1SitPc1NlUlJKU09XRUpLU2oKemltZGhMQWQ2b0NFUStlMzJlamx4ajZ4ZHNDUkFrQlZEU0UrK25MbFhQUlc1YjJINjhRR3IyS3p2c3ZTNVJXeQpocENFSW9FRm9saU0vUURaZDhqRDZBdW1XQXlaUzY1T0VNRWwvMWRMRlBlREdMblMrQVByQWtCT3dQMDQ4c2Q4ClB0QTJkaWVJTVdLSlhHMGdiL0ZpVTVxVDBQZU1kdHEvakNPVDZuN1kxd3RQK2hXV05nVHJaTHZCeklDUzdCZ1cKQWxWZ0Izd0xTL3Z6Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
      - PUB_KEY=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNaakNDQWMrZ0F3SUJBZ0lVWkZxOWxra1BHaWk5MkhISFI4VjlGck1Ld1V3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtHQTFVRUJoTUNSMEl4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB5TXpBNU1UTXhNak00TWpWYUZ3MHlOREE1Ck1USXhNak00TWpWYU1FVXhDekFKQmdOVkJBWVRBa2RDTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXdnWjh3RFFZSktvWklodmNOQVFFQgpCUUFEZ1kwQU1JR0pBb0dCQU9RT2h4SEVpTXB2MER2dmVWZXFMUU40Tkd0cTh0SmVNMGdwUVZIM3pFMjRsdmtnCnA4bzRXckRTeGdvcUlGZ0NSMk9nOXV5eGo2a3ZqWGV4K0t0M3hTdWdURWl6K3hrdllBSlhzZHNwTEtWU01RWE8KQ0Y4MStRMVFUVnFXVlR5ZDVjOWhYc21uVjNDVlJFMmUreFpRaFQ4WTJGanZuQ1ZoV0Jpd1lDaUFwT3dsQWdNQgpBQUdqVXpCUk1CMEdBMVVkRGdRV0JCUjdzeEEyeHZqSXJCK3JZL212RVFCdGFyaXpqVEFmQmdOVkhTTUVHREFXCmdCUjdzeEEyeHZqSXJCK3JZL212RVFCdGFyaXpqVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNEdCQUVYUWJreGhFVXFWMHZuMnNnd3ZqK0I2VHE3Wmk0RU1JUlFiNzM0L1F3U2RhTVY0dVBERwpDS2RTZ2c4dlIxZDliSCsyL1RIeklHRjV4K2lEUlhUVzJ1YnBRS2ZaVEY5czhjUm9LQmNZY21OMTg4RUw0dEZHCmVWRFBVVk9ZdDhNd3ZhbUVWUnhzYnVnTHc2RlY0QlVySnhpUGRNVHd2V1MzdHdDOTJXYm5ycGdzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    volumes:
      - app:/var/www/html

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: 082624796438.dkr.ecr.eu-west-2.amazonaws.com/sjcadmin/nginx
    hostname: nginx
    depends_on:
      - app
    networks:
      default:
        aliases:
          - auth.southamptonjiujitsu.local
          - monolith.southamptonjiujitsu.local

  terraform:
    build:
      context: ./terraform
    environment:
      - AWS_ACCESS_KEY_ID=$TERRAFORM_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$TERRAFORM_AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - terraform:/app
  
  database:
    image: postgres:14.5
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rand0m!
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/_init.sql

volumes:
  app:
  terraform:
