services:
  app:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - app:/var/www/html

  npm:
    build:
      context: .
      dockerfile: Dockerfile.npm
    entrypoint: npm
    command: build
    volumes:
      - type: volume
        source: app
        target: /app

volumes:
  app:
