services:
  app:
    build:
      context: .
      target: base
    volumes:
      - app:/var/www/html

  npm:
    build:
      context: .
      dockerfile: Dockerfile.npm
    volumes:
      - type: volume
        source: app
        target: /app

volumes:
  app:
