include:
  - services/docker-compose.override.yml
  - workers/docker-compose.override.yml

services:
  frontend:
    ports:
      - 8080:5173
    volumes:
      - ./frontend:/app
  
  frontend-members:
    ports:
      - 8081:5173
    volumes:
      - ./frontend-members:/app

  app:
    build:
      context: .
      target: dev-runtime
    networks:
      default:
        aliases:
          - admin.southamptonjiujitsu.local
          - members.southamptonjiujitsu.local
    volumes:
      - ./sjcadmin:/app/sjcadmin
      - ./static:/app/static
      - ./templates:/app/templates
      - ./poetry.lock:/app/poetry.lock
      - ./poetry.toml:/app/poetry.toml
      - ./pyproject.toml:/app/pyproject.toml

  gateway:
    ports:
      - 8000:8000
    volumes:
      - ./config/nginx:/etc/nginx/conf.d

  database:
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI for testing

  terraform:
    volumes:
      - ./terraform:/app

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,sqs,sns
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DEBUG=1
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./workers:/app/workers
