services:
  app:
    build:
      context: .
      target: dev-runtime
    environment:
      - API_ROOT=http://api.southamptonjiujitsu.local:8000
      - DJANGO_SETTINGS_MODULE=sjcadmin.settings
      - DJANGO_SECRET_KEY="*(%z)+p^f+*&!zdv$j_ipce+)ru+f+g91udo2i&=1l1r6deyet"
      - ENVIRONMENT_NAME=local
      - PGHOST=database
      - PGPASS=Rand0m!
      - SJJ_S3_ACCESS_KEY=AKIARGPGSK4LMB2A3YFS
      - SJJ_S3_SECRET_KEY=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
      - EMAIL_HOST=mail
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=false
      - EMAIL_HOST_USER='username'
      - EMAIL_HOST_PASSWORD='password'
    networks:
      default:
        aliases:
          - admin.southamptonjiujitsu.local
          - api.southamptonjiujitsu.local
          - members.southamptonjiujitsu.local
    volumes:
      - .:/app

  nginx:
    ports:
      - 8000:8000
    volumes:
      - ./config/nginx:/etc/nginx/conf.d

  static:
    build:
      target: dev-runtime
    volumes:
      - .:/app
    ports:
      - 9000:80

  base:
    build:
      context: .
      target: base
    environment:
      - DJANGO_SETTINGS_MODULE=sjcadmin.settings
      - DJANGO_SECRET_KEY="*(%z)+p^f+*&!zdv$j_ipce+)ru+f+g91udo2i&=1l1r6deyet"
      - ENVIRONMENT_NAME=local
      - PGPASS=Rand0m!
    working_dir: /app
    volumes:
      - .:/app

  database:
    image: postgres:14.5
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rand0m!
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/_init.sql
      - ./pgdata:/var/lib/postgresql/data

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI for testing

  terraform:
    volumes:
      - ./terraform:/app

  attendance-worker:
    build:
      target: base
    volumes:
      - ./workers/attendance:/app

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,sqs,sns
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DEBUG=1
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./workers:/app/workers

