services:
  app:
    build:
      context: .
      target: dev-runtime
    environment:
      - DJANGO_SETTINGS_MODULE=sjcadmin.settings
      - DJANGO_SECRET_KEY="*(%z)+p^f+*&!zdv$j_ipce+)ru+f+g91udo2i&=1l1r6deyet"
      - ENVIRONMENT_NAME=local
      - PGPASS=Rand0m!
      - SJJ_S3_ACCESS_KEY=foo
      - SJJ_S3_SECRET_KEY=bar
    ports:
      - 8000:8000
    volumes:
      - .:/app
  
  npm:
    command: ["run", "dev"]
    volumes:
      - .:/app

  base:
    build:
      context: .
      target: base
    environment:
      - DJANGO_SETTINGS_MODULE=sjcadmin.settings
      - DJANGO_SECRET_KEY="*(%z)+p^f+*&!zdv$j_ipce+)ru+f+g91udo2i&=1l1r6deyet"
      - ENVIRONMENT_NAME=local
      - PGPASS=Rand0m!
    working_dir: /app
    volumes:
      - .:/app

  database:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rand0m!
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./pgsetup.sql:/docker-entrypoint-initdb.d/_init.sql
      - ./pgdata:/var/lib/postgresql/data
