services:
  app:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=sjcadmin.settings
      - ENVIRONMENT_NAME=local
      - PGPASS=Rand0m!
