include:
  - services/docker-compose.yml
  - workers/docker-compose.yml

services:
  app:
    build:
      context: .
      target: prod-runtime
    image: 082624796438.dkr.ecr.eu-west-2.amazonaws.com/sjcadmin/app
    volumes:
      - app:/var/www/html

  static:
    build:
      context: .
      dockerfile: Dockerfile.static
      target: prod-runtime
    image: 082624796438.dkr.ecr.eu-west-2.amazonaws.com/sjcadmin/static
    hostname: static

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: 082624796438.dkr.ecr.eu-west-2.amazonaws.com/sjcadmin/nginx
    hostname: nginx
    ports:
      - 8000:8000
    depends_on:
      - app
      - static

  terraform:
    build:
      context: ./terraform
    environment:
      - AWS_ACCESS_KEY_ID=$TERRAFORM_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$TERRAFORM_AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - terraform:/app
  
  database:
    image: postgres:14.5
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rand0m!
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  app:
  terraform:
