include:
  - services/docker-compose.override.yml
  - workers/docker-compose.override.yml

services:
  app:
    build:
      context: .
      target: dev-runtime
    depends_on:
      - api-gateway
    environment:
      - API_ROOT=http://api.southamptonjiujitsu.local:9000
      - API_KEY=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZiB5b3UgYXJlIHJlYWRpbmcgdGhpcyI6InlvdSBoYXZlIHRvbyBtdWNoIHRpbWUgb24geW91ciBoYW5kcyJ9.a2Vm6eY2cbWIhwteh1lK3zn8sb6gH7rk38SNtnm_6XKvz2vnNqajXx2uxYtF7Cwl9n-f1Vn7FVg8y2OwWknkqDg3OY2leNN6GbDvdZpDiafYipVssOqo3Lq361vQCzSHtHnBlMu_Gf_EIwSqT1gsAtRwJlZ2oOD_otIVlpap7bU
      - DJANGO_SETTINGS_MODULE=sjcadmin.settings
      - DJANGO_SECRET_KEY="*(%z)+p^f+*&!zdv$j_ipce+)ru+f+g91udo2i&=1l1r6deyet"
      - ENVIRONMENT_NAME=local
      - PGHOST=database
      - PGPASS=Rand0m!
      - SJJ_S3_ACCESS_KEY=AKIARGPGSK4LMB2A3YFS
      - SJJ_S3_SECRET_KEY=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
      - EMAIL_HOST=mail
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=false
      - EMAIL_HOST_USER='username'
      - EMAIL_HOST_PASSWORD='password'
    networks:
      default:
        aliases:
          - admin.southamptonjiujitsu.local
          - members.southamptonjiujitsu.local
    volumes:
      - .:/app

  static:
    build:
      target: dev-runtime
    volumes:
      - .:/app

  gateway:
    ports:
      - 8000:8000
    volumes:
      - ./config/nginx:/etc/nginx/conf.d

  base:
    build:
      context: .
      target: base
    environment:
      - DJANGO_SETTINGS_MODULE=sjcadmin.settings
      - DJANGO_SECRET_KEY="*(%z)+p^f+*&!zdv$j_ipce+)ru+f+g91udo2i&=1l1r6deyet"
      - ENVIRONMENT_NAME=local
      - PGPASS=Rand0m!
    working_dir: /app
    volumes:
      - .:/app

  database:
    ports:
      - 5432:5432
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/_init.sql
      - ./pgdata:/var/lib/postgresql/data

  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI for testing

  terraform:
    volumes:
      - ./terraform:/app

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,sqs,sns
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - DEBUG=1
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./workers:/app/workers
