# Generated by Django 4.1.2 on 2022-10-30 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('expires', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=120, null=True)),
                ('profile_dob', models.DateField(null=True)),
                ('profile_phone', models.CharField(max_length=32, null=True)),
                ('profile_email', models.EmailField(max_length=254, null=True)),
                ('profile_address', models.TextField(blank=True, null=True)),
                ('allowed_trial_sessions', models.IntegerField()),
                ('licence', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sjcadmin.licence')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sjcadmin.student')),
            ],
        ),
    ]
