# Generated by Django 4.1.3 on 2022-11-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0002_attendance_paid_alter_student_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='complementary',
            field=models.BooleanField(default=False),
        ),
    ]
