# Generated by Django 4.1.3 on 2022-11-09 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0003_attendance_complementary'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 7, 57, 11, 179774)),
        ),
    ]
