# Generated by Django 4.1.3 on 2022-12-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='_course',
            field=models.ForeignKey(db_column='course_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sjcadmin.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='_course',
            field=models.ForeignKey(db_column='course_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sjcadmin.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='_used',
            field=models.BooleanField(db_column='used', default=False),
        ),
    ]
