# Generated by Django 4.1.3 on 2023-01-08 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sjcadmin', '0009_student__courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='_creator',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
