# Generated by Django 4.1.3 on 2023-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0010_student__creator_alter_note__author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tenant_uuid',
            field=models.UUIDField(blank=True, null=True, default='7fe20f85-c6b0-4c67-8b68-c033367c92a5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='tenant_uuid',
            field=models.UUIDField(blank=True, null=True, default='7fe20f85-c6b0-4c67-8b68-c033367c92a5'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tenant_uuid'], name='sjcadmin_co_tenant__683098_idx'),
        ),
    ]
