# Generated by Django 4.1.3 on 2023-09-21 14:26

from django.db import migrations, models
import uuid


def insert_default_tenant(apps, schema_editor):
    Tenant = apps.get_model('sjcadmin', 'Tenant')
    t = Tenant(uuid='7fe20f85-c6b0-4c67-8b68-c033367c92a5', name='Southampton Jiu Jitsu')
    t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0011_course_tenant_uuid_student_tenant_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RunPython(insert_default_tenant),
    ]
