# Generated by Django 4.1.3 on 2023-09-25 07:43

from django.db import migrations, models


def fill_creator_name(apps, schema_editor):
    Student = apps.get_model('sjcadmin', 'Student')
    User = apps.get_model('sjcauth', 'User')

    def _username(uuid):
        u = User.objects.get(_uuid=uuid)
        if u:
            return u.email
        return 'Anonymous User'

    for student in Student.objects.all():
        username = _username(student._creator)
        student._creator_name = username
        student.save()


class Migration(migrations.Migration):
    dependencies = [
        ('sjcadmin', '0012_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='_creator_name',
            field=models.TextField(max_length=120, null=True),
        ),
        # migrations.RunPython(fill_creator_name),
    ]
