# Generated by Django 4.1.3 on 2023-10-06 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0014_student_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
