# Generated by Django 4.1.3 on 2023-10-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0015_alter_student_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('type', models.TextField(default='time')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sjcadmin.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sjcadmin.student')),
            ],
        ),
    ]
