# Generated by Django 4.1.3 on 2023-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0016_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
