# Generated by Django 4.1.3 on 2023-10-21 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjcadmin', '0017_alter_subscription_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None),
        ),
    ]
