# Generated by Django 4.1.3 on 2023-09-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjcauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_uuid',
            field=models.UUIDField(default='7fe20f85-c6b0-4c67-8b68-c033367c92a5'),
            preserve_default=False,
        ),
    ]
