# Generated by Django 4.1.3 on 2023-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjcauth', '0002_user_tenant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
