services:
  attendance-service:
    build:
      context: ./attendance
      target: dev-runtime
    depends_on:
      - database
    environment:
      - ENVIRONMENT_NAME=local
      - PGHOST=database
      - PGPASS=Rand0m!

  api-gateway:
    image: nginx:latest
    depends_on:
      - attendance-service
    networks:
      default:
        aliases:
          - api.southamptonjiujitsu.local
