# Generated by Django 4.1.3 on 2023-09-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(db_column='paid', default=False)),
                ('complementary', models.BooleanField(db_column='complementary', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', db_index=True)),
                ('course_uuid', models.UUIDField(db_column='course_uuid', db_index=True)),
                ('student_uuid', models.UUIDField(db_column='student_uuid', db_index=True)),
                ('resolution', models.OneToOneField(blank=True, db_column='resolution', null=True, on_delete=django.db.models.deletion.CASCADE, to='sjcattendance.resolution')),
            ],
        ),
    ]
